targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          # Only run `json_serializable` on source under `lib/models`.
          - lib/models/**/*.dart
      freezed:
        generate_for:
          # Only run `freezed` on source under `lib/bloc`.
          - lib/bloc/**/*.dart
        options:
          format: false
      auto_route_generator:auto_router_generator:
        options:
          ignore_for_file:
            - inference_failure_on_instance_creation
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/ui/**/view/*.dart
          - lib/ui/**/view/**/*.dart
          - lib/ui/**/shell/*.dart
          - lib/ui/**/screens/*.dart
          - lib/app/view/app.dart
          - lib/router/wrappers/*_page.dart