// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkti7nQ5Ws8hvO8k-hGiN3jNahGFZCJ6w',
    appId: '1:1033180258831:web:5f5426e14300760bfd397a',
    messagingSenderId: '1033180258831',
    projectId: 'samgyup-serve',
    authDomain: 'samgyup-serve.firebaseapp.com',
    storageBucket: 'samgyup-serve.firebasestorage.app',
    measurementId: 'G-JDJ1T3YBT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC_qQPleaUh-RLekelQCjekZzMaKdIqQ4',
    appId: '1:1033180258831:android:bebcab7712fc7f09fd397a',
    messagingSenderId: '1033180258831',
    projectId: 'samgyup-serve',
    storageBucket: 'samgyup-serve.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsamxdqJmegVMsz5kMS7Fr4eiyl448Dmc',
    appId: '1:1033180258831:ios:f8353cefce2cc785fd397a',
    messagingSenderId: '1033180258831',
    projectId: 'samgyup-serve',
    storageBucket: 'samgyup-serve.firebasestorage.app',
    iosBundleId: 'com.example.verygoodcore.samgyup-serve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsamxdqJmegVMsz5kMS7Fr4eiyl448Dmc',
    appId: '1:1033180258831:ios:8063e47d5835e90bfd397a',
    messagingSenderId: '1033180258831',
    projectId: 'samgyup-serve',
    storageBucket: 'samgyup-serve.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkti7nQ5Ws8hvO8k-hGiN3jNahGFZCJ6w',
    appId: '1:1033180258831:web:ce1b2ba2d4daed03fd397a',
    messagingSenderId: '1033180258831',
    projectId: 'samgyup-serve',
    authDomain: 'samgyup-serve.firebaseapp.com',
    storageBucket: 'samgyup-serve.firebasestorage.app',
    measurementId: 'G-385Q6EKMWS',
  );
}
