export 'shell/inventory_shell_page.dart';
export 'view/create/inventory_add_page.dart';
export 'view/details/inventory_details_page.dart';
export 'view/edit/inventory_edit_page.dart';
export 'view/inventory_page.dart';
export 'view/list/category/inventory_category_list_page.dart';
export 'view/list/status/inventory_status_list_page.dart';
export 'view/stock/add_stock_page.dart';
export 'view/subcategories/subcategories_page.dart';
