name: Main CI/CD Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "docs/**"
      - ".gitignore"
      - "LICENSE"

permissions:
  contents: write

jobs:
  bump-version:
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[no release]')"
    uses: ./.github/workflows/bump.yaml

  create-tag:
    needs: bump-version
    runs-on: ubuntu-latest
    if: needs.bump-version.outputs.new_version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Pull latest changes
        run: git pull origin main

      - name: Create and push tag
        run: |
          new_version="${{ needs.bump-version.outputs.new_version }}"
          tag_name="v$new_version"

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git tag -a "$tag_name" -m "Release $new_version"
          git push origin "$tag_name"
          echo "Created and pushed tag: $tag_name"

  release:
    needs: [bump-version, create-tag]
    uses: ./.github/workflows/release.yaml
    with:
      version: ${{ needs.bump-version.outputs.new_version }}
