targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/src/models/*.dart
      freezed:
        generate_for:
          - lib/src/models/*.dart
        options:  
          format: false
